version: '3'

services:
  api:
    build: .
    container_name: pastebin-api
    ports:
      - '9000:9000'
    environment:
      - MONGO_URI=mongodb://root:pastebin_mongo_password@mongodb:27017/Pastebin?authSource=admin

  mongodb:
    image: mongo
    container_name: pastebin-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pastebin_mongo_password
    ports:
      - '27017:27017'

# EOF
